server:
  port: 8085
spring:
  application:
    name: scaffold
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/test_web
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB
springdoc:
  swagger-ui:
    enabled: true
    persist-authorization: false
app:
  name: GTS Active Scaffold
  version: 1.0.0
  environment: dev
  security:
    jwt-secret: "this-is-a-very-long-secure-secret-key-123456"
    jwt-expiration-ms: 3600000
    refresh-token-expiration-ms: 86400000
  cors:
    allowed-origins:
      - http://localhost:3000
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE